### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by deukyeon** [ut-osa/assise#13]
Hello,

I ran into some compiling errors when I compiled the code out of the box.

Errors happened when I tried installing dependencies and compiling libfs like the screenshots below.
![compile_libfs](https://user-images.githubusercontent.com/6286708/138024512-317702d9-5a8a-4c8d-b0ee-2a4d0a5ec788.png)

![install_deps](https://user-images.githubusercontent.com/6286708/138024517-c56466a9-5c40-46ad-b0d6-e6ef4e922e8f.png)

My system uses Debian 11 and gcc/g++ version 10.2.1.

**Comment by wreda** [comment]
I suspect these errors are only raised by later versions of gcc. I'll look into this as soon as I have free cycles.

In the meantime, can you try downgrading to an earlier version of gcc (e.g. version 7.5) and recompiling Assise?
