### ISSUE TITLE
Program error in 16+ threads

### ISSUE THREAD

**Issue by chfeng-cs** [ut-osa/assise#2]
Hello, we would like to test Assise on our cluster. Assise works well in the case of multi-thread.  But when the number of threads increases to 16, Assise stops to work and shows the following error message:

> Failed to acquire msg buffer. Buffer is locked. [error code: 0]

Do you have any ideas and suggestions？

**Comment by wreda** [comment]
Getting to this now.

In case you're still interested, this error indicates that you have an insufficient number of message buffers allocated for RPCs. To override this configuration, you should go to $ASSISE_DIR$/libfs/lib/rdma, increase MAX_BUFFER in globals.h, and then re-compile the library.

To be safe, set MAX_BUFFER to 2x the number of threads you intend to use (or any higher value).
