### ISSUE TITLE
Hitting assertion failure during replication

### ISSUE THREAD

**Issue by rohankadekodi** [ut-osa/assise#23]
Hello,

I have configured 32GB of emulated NVM on my machine using the steps mentioned in the repository for a 2-node cluster using RDMA.I have set the dev sizes to 8GB NVM using `utils/change_dev_size.py 8 0 0`

Then I start the cluster, and try to run the example mentioned in the repository: `./tests/run.sh iotest sw 2G 4K 1`

However, libfs fails with the assertion (most of the times):
```
Assertion failed: src/distributed/replication.c, start_rsync_session(), 995 at 'peer->remote_start <= peer->start_digest'
```

Could I get help with this issue? I am happy to provide access to my cluster if that helps solve the issue.

**Comment by wreda** [comment]
This should now be fixed!
