### ISSUE TITLE
Multi-thread Filebench

### ISSUE THREAD

**Issue by SJTUqizhenlin** [ut-osa/assise#28]
Hi,

I am interested with assise and currently conducting some build and test work on it.

Here is a problem I met when using filebench as benchmark tool:

I have build the filebench.mlfs executable file in "assise/bench/filebench", and successfully run the "run_varmail.sh" script and get good results.
But when I change the "varmail_mlfs.f", specifically I change the "nrthreads" parameter from 1 to 2, there will be a crash.

As you know, multi-thread performance is always important, and I am really willing to see the results of filebench on assise.

Could you please help me to find out a way to run filebench with multi-thread? Thanks a lot.

**Comment by wreda** [comment]
Assise currently doesn't have proper multi-threading support.

This may be addressed in a future patch but, for the time being, you will have to limit yourself to single-threaded Filebench configurations.
